### ISSUE TITLE
Using Xaml and Maui Reactor

### ISSUE THREAD

**Issue by TedMobile** [adospace/rive-app#3]
Hey
what you produce is absolutely brilliant, and they look sooo good.

I have to admit that I have not played much with animation 

The reality is the most of us are stuck with Xaml because we have large applications that we are porting to Maui and re-writing using your framework is no starter to the business.

The ask:
Is it possible to mix Maui Xaml and use rive-app?

I would like our menu to have the same transitions you do in your rive app page but using shell. Can I mix the 2? 

All our app is shell navigation driven so I cant just remove it, but I would like to have those beautiful effects in the menu that you have in your Rive-app.

I hope what I am asking makes sense but whether can be done is another matter.

Grazie in anticipo

**Comment by adospace** [comment]
Hi, 
thanks for your interest, actually I'm about to publish a new feature that will allow you to place MauiReactor components inside a XAML-based standard application.
I think I'll release it very soon, before the end of the week:
https://github.com/adospace/reactorui-maui/issues/14#issuecomment-1559794755

**Comment by TedMobile** [comment]
that will be a game changer expecially if you do some demo like rive app or anything were we mix the 2.

brilliant looking forward to it
